### ISSUE TITLE
关于正则项

### ISSUE THREAD

**Issue by yangkailun** [huangtinglin/Knowledge_Graph_based_Intent_Network#10]
首先十分感谢您的工作以及开源代码，从中我学习了很多。
关于代码中的正则项我有点疑惑，因为它与论文中提到的不同。代码中的正则项只包含用户，物品项，似乎没有其他模型的参数？对于这一点您怎么看？

**Comment by huangtinglin** [comment]
感谢您对我们工作的关注。
您说的正则项是指公式(16)里的independence loss与L2正则化项吗？independence loss在KGIN文件第188行计算，L2正则化是在KGIN文件第319到323行计算。我不太确定您说的不同是指什么，能否详细地说明下？谢谢！

**Comment by yangkailun** [comment]
感谢回复。我的疑惑是在L2正则项，例如论文中的公式（16）中的L2正则项还包含关系向量等，在KGIN文件中的第319到323行只有users和items的向量，其他的没有体现？

**Comment by huangtinglin** [comment]
代码里的实现确实没包括关系向量，算是和论文之间的一个bug吧。。是一个疏忽非常抱歉。

**Comment by yangkailun** [comment]
明白，再次感谢解惑。
