### ISSUE TITLE
关于复现

### ISSUE THREAD

**Issue by yangkailun** [huangtinglin/Knowledge_Graph_based_Intent_Network#11]
再次感谢您的开源代码！
最近在用您的代码跑实验的时候，发现完全相同的两次实验的评估结果不完全一样。这种情况是否正常？我注意到您的代码中已经有随机数的固定和一些复现的设置（这些代码我都是保持原状）。

**Comment by huangtinglin** [comment]
不同服务器之间应该还是会有变化，因为计算的精度不同。同个服务器之间我自己尝试还是会有波动，没怎么去细究，因为变化很小。

**Comment by yangkailun** [comment]
我这边实验也是变化很小。感谢您的回复！
