### ISSUE TITLE
实验结果

### ISSUE THREAD

**Issue by data-ming-and-application** [huangtinglin/Knowledge_Graph_based_Intent_Network#12]
想问一下作者，为什么实验的数据集是一样的，结果会如此不同，请问作者知道是什么原因吗？Knowledge   graph convolutional networks for recommender systems，19年的文章，通常采取所有的items去除训练集的方式，实验的结果不在同一个量纲范围内。

**Comment by huangtinglin** [comment]
您好，感谢您对我们工作的关注！
您说的那篇是KGCN，他所用的数据集和我们是不一样的，您可以仔细对照看看statistics表格。而且KGCN的源码在评估阶段，计算recall指标时是sample一部分的user来测试，偏差较大。

**Comment by rdyan0053** [comment]
> 想问一下作者，为什么实验的数据集是一样的，结果会如此不同，请问作者知道是什么原因吗？Knowledge graph convolutional networks for recommender systems，19年的文章，通常采取所有的items去除训练集的方式，实验的结果不在同一个量纲范围内。

请教一下，关于这个实验，您训练花了多长时间
