### ISSUE TITLE
in the code latent_emb embedding has two ways?

### ISSUE THREAD

**Issue by wgchen** [huangtinglin/Knowledge_Graph_based_Intent_Network#13]
hi, when i see the code, i have Puzzled
![image](https://user-images.githubusercontent.com/7655026/131352216-250fe3d3-60bb-4b61-a7cc-fd6382b36172.png)
in the paper, formula 7 and formula  8, ep why is not same in the code, why cal user intent att use a new init embedding？

**Comment by huangtinglin** [comment]
Sorry for the late reply. In the implementation, we apply the additional embedding to model the user intent instead of directly using the user embedding since we found that it will improve the performance.
