### ISSUE TITLE
怎么恢复保存的模型的参数

### ISSUE THREAD

**Issue by XUPT-guoruihan** [huangtinglin/Knowledge_Graph_based_Intent_Network#15]
您好！非常感谢您分享的代码  我注意到您的代码中有save的相关代码
  """save weight"""
            if ret['recall'][0] == cur_best_pre_0 and args.save:
                torch.save(model.state_dict(), args.out_dir + 'model_' + args.dataset + '.ckpt')
但是我发现下一次训练的时候并没有加载保存的参数，请问您的代码中实现恢复模型的相关代码了吗？

**Comment by huangtinglin** [comment]
感谢您对我们工作的关注！代码中暂时未实现加载模型，未来会考虑添加的。

**Comment by XUPT-guoruihan** [comment]
感谢您的回复！祝工作顺利
