### ISSUE TITLE
A question about equation7

### ISSUE THREAD

**Issue by cabbgae** [huangtinglin/Knowledge_Graph_based_Intent_Network#17]
老师您好：
    我想询问一下公式7中1/Nu这个式子在代码何处体现出来`user_agg = user_agg * (disen_weight * score).sum(dim=1) + user_agg # [n_users, channel]`，是我找的地方不对吗？烦请老师解答一下。
期待您的回复

**Comment by huangtinglin** [comment]
Hi您好，我不是老师呢只是一个学生呢。我刚刚确认了下确实是没求平均，这里有疏忽非常抱歉。不过这对模型影响不大，因为后续有normalize操作。

**Comment by cabbgae** [comment]
十分感谢您的回答，最近一直卡在这里，万分感谢

**Comment by huangtinglin** [comment]
好的，欢迎交流。
