### ISSUE TITLE
关于KGAT等基线方法实验结果与KGAT原论文中的不同

### ISSUE THREAD

**Issue by yangkailun** [huangtinglin/Knowledge_Graph_based_Intent_Network#18]
感谢您们的开源工作，我从中学到了很多。有一个疑问希望获得答案。
我在做对比实验时，发现KGIN与KGAT论文中使用了相同的Amazon，Last数据集和同样的评估指标，但是为什么两篇论文中的结果recall相近，ndcg却有较大的差距？

**Comment by huangtinglin** [comment]
KGAT使用的ndcg指标计算有误，具体可以参考在作者的另一个repo的readme：

https://github.com/xiangwang1223/kgpolicy/blob/master/README.md

**Comment by yangkailun** [comment]
十分感谢您的解惑！
