### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by hhdo** [huangtinglin/Knowledge_Graph_based_Intent_Network#19]
dataloader里的_bi_norm_lap方法中的拉普拉斯矩阵计算那里是否应为I-D^{-1/2}AD^{-1/2}

**Comment by huangtinglin** [comment]
抱歉迟复，您可以参考下GCN[1]里的公式推导，实际使用的为D^{-1/2}AD^{-1/2}。

[1] Semi-Supervised Classification with Graph Convolutional Networks
