### ISSUE TITLE
negative cor

### ISSUE THREAD

**Issue by FloatingMaple** [huangtinglin/Knowledge_Graph_based_Intent_Network#2]
i run your code several times and always get negative cor num
`
start training ...
using time 496.1616, training loss at epoch 0: 298.6853, cor: -103918.234375
`
or
`
start training ...
using time 636.8174, training loss at epoch 0: 299.3976, cor: -103918.351562
+-------+-------------------+--------------------+--------------------+----------------------------------------------------------+----------------------------------------------------------+----------------------------------------------------------+----------------------------------------------------------+
| Epoch |   training time   |    tesing time     |        Loss        |                          recall                          |                           ndcg                           |                        precision                         |                        hit_ratio                         |
+-------+-------------------+--------------------+--------------------+----------------------------------------------------------+----------------------------------------------------------+----------------------------------------------------------+----------------------------------------------------------+
|   1   | 636.8162143230438 | 137.00747871398926 | 194.09571838378906 | [0.07513288 0.09760893 0.11306548 0.12481185 0.13517161] | [0.06848064 0.07576022 0.08097082 0.08491058 0.08831252] | [0.02926674 0.02149495 0.01776641 0.01546985 0.01389799] | [0.26474582 0.34498854 0.39756429 0.43486379 0.46601035] |
+-------+-------------------+--------------------+--------------------+----------------------------------------------------------+----------------------------------------------------------+----------------------------------------------------------+----------------------------------------------------------+

using time 636.9025, training loss at epoch 2: 170.9751, cor: -113220.000000
using time 636.6866, training loss at epoch 3: 157.5762, cor: -113220.000000
using time 637.4699, training loss at epoch 4: 149.2337, cor: -113220.000000
`

it seems something has error?

**Comment by huangtinglin** [comment]
Hi.
The possible reason is the default setting of temperature. Actually, the recommended implementation of independence modeling is the distance correlation. You can get a similar training log as our provided one when using it. The code is updated. Thanks!

**Comment by FloatingMaple** [comment]
Hey, Huang.
i got the lastest code and try with your data, i think it worked.
Then i try to use ml-1m , but the trainging result seems not good, metrics more and more less with training. Would u give some suggestion about this? Thanks 

| Epoch |   training time   |    tesing time     |       Loss      |                          recall                          |                           ndcg                           |                        precision                         |                        hit_ratio                         |

|   1   | 57.72314143180847 | 3.1452457904815674 | 159.40673828125 | [0.03572149 0.06051997 0.08061825 0.09762777 0.11448082] | [0.03333848 0.04155729 0.04862622 0.05484019 0.06108911] | [0.0259109  0.02282627 0.02074638 0.01944352 0.01885558] | [0.33454786 0.45793309 0.53097052 0.58959921 0.64673733] |

|   9   | 57.23646378517151 | 3.074538230895996 | 115.88475036621094 | [0.03477755 0.05941059 0.08113446 0.09891487 0.11760145] | [0.0323038  0.04072892 0.04850209 0.05495365 0.0614803 ] | [0.02043723 0.01819311 0.01716076 0.01634233 0.01595727] | [0.27757536 0.41189135 0.50298112 0.56989069 0.62620073] |

|   19  | 57.711427450180054 | 3.0931742191314697 | 100.62030029296875 | [0.03349217 0.05688522 0.07705439 0.09466011 0.11194279] | [0.02910566 0.03734144 0.04443465 0.05070886 0.05663394] | [0.01847466 0.01642514 0.01523407 0.01457643 0.01413713] | [0.25571381 0.38390195 0.47466048 0.54372309 0.60052998] |

|   29  | 56.89892339706421 | 3.079301118850708 | 91.31163024902344 | [0.03360074 0.0569907  0.07782389 0.09650974 0.11325721] | [0.02882474 0.03706562 0.04440383 0.05092734 0.05654666] | [0.01803577 0.01602352 0.01499669 0.01435699 0.01375124] | [0.25173899 0.37843657 0.47234184 0.5382577  0.59456774] |

|   39  | 57.0876579284668 | 3.1588938236236572 | 84.93949127197266 | [0.03449371 0.05762298 0.07711679 0.09671727 0.11534958] | [0.02911043 0.0374106  0.04431393 0.05102487 0.05733699] | [0.01777907 0.01581236 0.01463785 0.01411477 0.01379596] | [0.24594237 0.3759523  0.4673733  0.53858894 0.60400795] |

**Comment by huangtinglin** [comment]
Could you please provide more details? Such as the statistics of the dataset, the construction of the knowledge graph. Thanks!

**Comment by FloatingMaple** [comment]
yeah, the dataset is MovieLens-1M, kg is build by infos got from TMDb about movie genre,actor,profile person,etc. it has 6,000+ users and 2,900+ movies, 10 relations 11,000+ entitiy.
i reformat as paper mentioned, change some parameter and got result like this.
| Epoch |   training time    |   tesing time   |        Loss       |                          recall                          |                           ndcg                           |                        precision                         |                        hit_ratio                         |
|   99  | 176.56601667404175 | 12.771240234375 | 57.38846969604492 | [0.04566443 0.07991236 0.10769833 0.13231826 0.15620177] | [0.03794198 0.05017191 0.06017274 0.06874119 0.07667055] | [0.02147356 0.01953423 0.0185176  0.01773579 0.01712747] | [0.29852478 0.46676612 0.57633018 0.66003647 0.72434941] |

i was wondering if u could upload some baselines code for compare , thx!

**Comment by huangtinglin** [comment]
We will do it in the future. Thanks for your attention!
