### ISSUE TITLE
How to get the result like Fig 5 in your paper?

### ISSUE THREAD

**Issue by panxianhaoo** [huangtinglin/Knowledge_Graph_based_Intent_Network#20]
like you mention in this issue #14 to get each intent's score, but how can I get the relation's score in a intent?
![image](https://user-images.githubusercontent.com/30815101/142756479-376db68a-13da-485c-a08a-2cf1e869dfe2.png)

**Comment by huangtinglin** [comment]
The score in fig5 is the corresponding attention score for the relation. We can calculate the attention score for each user to the intent (Eq.7-8), and we also can obtain the weight of each relation in intent (Eq. 1-2).
