### ISSUE TITLE
How do I know the total distribution and score of R in P in Figure 5

### ISSUE THREAD

**Issue by cabbgae** [huangtinglin/Knowledge_Graph_based_Intent_Network#21]
您好：
我该如何找到在图5中的p1和r56,r34之间的联系呢，是通过哪个代码体现的吗？
还有就是score是如何计算出来的，是用公式8计算的吗？   如果是，那么我该在哪找到这个score？
![图片1](https://user-images.githubusercontent.com/88702772/143672645-e577e38b-4e9b-4173-a56d-b5c353951051.png)

十分期待您的回答！

**Comment by cabbgae** [comment]
上面有个地方写错了，是p1和r65，r34

**Comment by huangtinglin** [comment]
抱歉迟复，模型会计算出不同user对不同intent的权重(Eq.7-8)，而每个intent内会含有不同relation的权重(Eq.1-2)。

**Comment by cabbgae** [comment]
十分感谢，这对我

**Comment by cabbgae** [comment]
但是我想知道r65和r34是如何在p1中体现出来的，也就是说，我不知道r在p中的具体分布

**Comment by huangtinglin** [comment]
这个权重是intent内relation的权重的softmax。

**Comment by cabbgae** [comment]
好的，谢谢您解答
