### ISSUE TITLE
latent_emb问题

### ISSUE THREAD

**Issue by shuaihuapei** [huangtinglin/Knowledge_Graph_based_Intent_Network#24]
你好，很感谢你们团队能提供代码，我有个问题，Recommender中定义了latent_emb，而根据论文中的公式1和公式2，latent_emb不应该是关系向量确定的吗？希望得到您的回复。

**Comment by huangtinglin** [comment]
您好，抱歉迟复。您可以参考下面这个issue：

https://github.com/huangtinglin/Knowledge_Graph_based_Intent_Network/issues/13
