### ISSUE TITLE
Lastfm数据集

### ISSUE THREAD

**Issue by Lilyzhangyanlin** [huangtinglin/Knowledge_Graph_based_Intent_Network#25]
你好~我想问一下Lastfm数据集中最后用于推荐的物品（item-list.txt中的内容）是原始数据中的tracks嘛？

感谢~

**Comment by huangtinglin** [comment]
您好，抱歉迟复。这个数据集最早是在[KGAT](https://github.com/xiangwang1223/knowledge_graph_attention_network)整理开源的，我并未参与那个项目，建议您去那个repo下咨询，谢谢您！

**Comment by Lilyzhangyanlin** [comment]
好滴~谢谢啦！
