### ISSUE TITLE
intent的embedding以及意图独立性时的参数等问题

### ISSUE THREAD

**Issue by 945168786** [huangtinglin/Knowledge_Graph_based_Intent_Network#26]
你好！感谢你们团队能提供代码供大家学习！这里有两个问题想问一下：
① 在论文中的ep，即意图的嵌入，应该是由关系嵌入计算得出的，但是在代码中是直接定义了一个latent_emb并直接使用，好像与文中不符（或者意图向量不是latent_emb？）。
② 在计算意图独立性时，论文中是用已经得到的ep进行计算，但是代码里用来计算的是参数是disen_weight_att，我理解这个参数是wrp，即关系r到意图p的一个可训练参数，这里也和原文中有些不同。

**Comment by 945168786** [comment]
Hello! Thanks to your team for making the code available for learning! Here are two questions I would like to ask.
① In the paper the ep, i.e. the embedding of the intent, is supposed to be calculated from the relational embedding, but in the code a latent_emb is defined and used directly, which seems to be inconsistent with the paper(or maybe the intent vector is not latent_emb?).
② In the calculation of intention independence, the paper is used to calculate the ep already obtained, but the code is used to calculate the parameter is disen_weight_att, I understand that this parameter is wrp in the paper, that is, a trainable parameter of the relationship r to intention p. Here is also a little different from the original text.
I hope you can answer some of these two questions.

**Comment by huangtinglin** [comment]
抱歉迟复。
1. 这个您可以参考这个issue：https://github.com/huangtinglin/Knowledge_Graph_based_Intent_Network/issues/13
2. 您说的是公式(2)里用到的wrp么，这个和disen_weight_att应该是一致的吧。

**Comment by 945168786** [comment]
我明白你第一问的意思了，您是使用了一个额外的embedding去建模用户的intent。
这里还有一个小问题，关于这个intent的。您前文的意图是希望能让intent代表两个关系的组合，如果是这样额外初始化一个embedding，要如何得到这个embedding代表哪两个关系呢，是计算这个intent与不同relation的距离吗？因为我对得到最后的case study的图非常感兴趣，所以想了解一下，望解答。

**Comment by huangtinglin** [comment]
intent的计算是针对所有的relation而言的，您可以将intent看成是relation的分布，有的权重会偏高有的会偏低。case study的图里某个relation的权重就是训练结束后计算intent时得到的该relation的权重。

**Comment by 945168786** [comment]
您的邮件已收到，如有需要，我将尽快回复。祝生活愉快！
     
                                                      初阳学院工科171余慧

**Comment by 945168786** [comment]
谢谢您的回复！我再仔细的看一下代码理解一下！

**Comment by huangtinglin** [comment]
好的，欢迎交流~

**Comment by 945168786** [comment]
您的邮件已收到，如有需要，我将尽快回复。祝生活愉快！
     
                                                      初阳学院工科171余慧
