### ISSUE TITLE
您好，论文内容有一处不解，冒昧请教

### ISSUE THREAD

**Issue by Jungle123456** [huangtinglin/Knowledge_Graph_based_Intent_Network#27]
对于每一对交互历史(u,i)，在引入intent之后，都会变成(u,p1,i),(u,p2,i),(u,p3,i),(u,p4,i)吗？也就是说意图集的4个p会对所有的interactions均有贡献吗？

**Comment by huangtinglin** [comment]
是的，您的理解没错
