### ISSUE TITLE
Some questions about Lastfm datasets

### ISSUE THREAD

**Issue by HUE96yhz** [huangtinglin/Knowledge_Graph_based_Intent_Network#3]
I'm sorry to bother you!
Could you please tell me which particular `Last-FM` data set you used in your paper? Is it the `LFM-1B UGP `data set in the website link you gave?
PS: The KGAT paper provides `lastfm` dataset address is https://grouplens.org/datasets/hetrec-2011/  Can the data of these two addresses be used?

**Comment by huangtinglin** [comment]
Hi! Sorry for the late reply. The Last-FM dataset used in KGIN is released by KGAT. You can check the detailed description in the paper.
