### ISSUE TITLE
Could you tell me the hardware information for the experiment?

### ISSUE THREAD

**Issue by BlueGhostZ** [huangtinglin/Knowledge_Graph_based_Intent_Network#4]
Thank you very much for openning source. 
I'd like to ask about the hardware of your experiment (GPU, memory size, etc.). Looking forward to your reply.

**Comment by BlueGhostZ** [comment]
@huangtinglin

**Comment by huangtinglin** [comment]
Sorry for the late reply. The experiments are conducted on a single Linux server with 512G RAM and 8 NVIDIA GeForce v100-32GB.

**Comment by BlueGhostZ** [comment]
Thank you for your reply.In the training log of Amazon-Book dataset, the training time of eachepoch is 800+ seconds, which is unacceptable. I used to use the whole last.FM Data sets (3 million interactions and 460000 + triplets) and also use Tesla V100 to train KGAT, and the average train time of each epoch is only 182 seconds. KGIN has no additional knowledge Graph representation learning(e.g. transR). Why does it spend so much time training?

**Comment by huangtinglin** [comment]
I think the most time-consuming procedure is calculating the equation (7)(10), which is implemented in the "KGIN" file (line 35-38).  Here I use the torch_scatter package to aggregate the neighbor embedding, and it can be further optimized or replaced by another efficient implementation.
