### ISSUE TITLE
About user representation aggregation

### ISSUE THREAD

**Issue by FloatingMaple** [huangtinglin/Knowledge_Graph_based_Intent_Network#5]
In the paper, user representation get from the Intenet Graph. Is IG just compose by user,intent,item (without entity about item)? 

And how to calculate high-order representation of user, like e_u^(3) ?
First calculate high-order representation of item e_i_(_2), Then got e_u^(3) by equation (6)(7)(8) in paper?

Thx reply .

**Comment by huangtinglin** [comment]
Following equation (11), we can obtain e_u^(3) by recursively executing equation (6).
