### ISSUE TITLE
How to realize the equation (12) in your paper?

### ISSUE THREAD

**Issue by BlueGhostZ** [huangtinglin/Knowledge_Graph_based_Intent_Network#8]
Hi, Huang.
The process of Relational Path-aware Aggregation realized on line 25-50 in your code (KGIN.py), and then sum representations of user and item up as the final representations(equtation(13) in your paper) on line 202-203 in your code (KGIN.py). But I can't find the process of  Capturing Relational Paths(the quation(12) in your paper). Where is this process implemented in your code?

Thank you very much for reading my questions. Your paper is very helpful to me. I look forward to your reply.

@huangtinglin

**Comment by huangtinglin** [comment]
Thanks for your attention. Following equation (11), the process (equation (13)) can be implemented by recursively executing equation (6)(9).

**Comment by BlueGhostZ** [comment]
Thank you very much for your reply. But I want to know how equation (12) is implemented in your code, not equation (13)
![Y)_48N@06J@N8%B LIV3UV](https://user-images.githubusercontent.com/71833100/114478902-ea1c8400-9c31-11eb-975c-ac7609114536.png)

Thank you very much for reading my questions. I look forward to your reply.

**Comment by huangtinglin** [comment]
Sorry, I made a mistake...Following equation (11), the process (equation (12)) can be implemented by recursively executing equation (6)(9), which is shown in the paper. Specifically, if we aggregate the user/item embedding L times (line 25-50), the obtained representations are equivalent to aggregate along the L-hop relational path.

**Comment by BlueGhostZ** [comment]
Thanks for your reply. I've got it.
